# .github/workflows/docs.yml
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TypeStrong/typedoc-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}